openapi: 3.0.3
info:
  title: Django DRF Ecommerce
  version: 1.0.0
  description: This is a sample API using DRF Spectacular
paths:
  /api/brand/:
    get:
      operationId: brand_list
      description: A simple Viewset for viewing all brands
      tags:
      - brand
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
          description: ''
  /api/category/:
    get:
      operationId: category_list
      description: A simple Viewset for viewing all categories
      tags:
      - category
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
  /api/product/:
    get:
      operationId: product_list
      description: A simple Viewset for viewing all products
      tags:
      - product
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    Category:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
      required:
      - name
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        brand:
          $ref: '#/components/schemas/Brand'
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          maxLength: 100
        description:
          type: string
        is_digital:
          type: boolean
      required:
      - brand
      - category
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
