# Generated by Django 5.1.1 on 2024-10-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_attribute_producttype_brand_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="productline",
            new_name="product_line",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="pid",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="productline",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_line_type",
                to="product.producttype",
            ),
        ),
        migrations.AddField(
            model_name="productline",
            name="weight",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="producttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.producttype",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_value_av",
                        to="product.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producte_value_pl",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_value", "product")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="attribute_value",
            field=models.ManyToManyField(
                related_name="product_attr_value",
                through="product.ProductAttributeValue",
                to="product.attributevalue",
            ),
        ),
    ]
